template: app-manifests
deployments:
  development:
    target: development
    clusters: 1
    values:
      repository: https://github.com/kaizentm/gitops-manifests
      branch: dev
      folder: rancher-hello-world
  production:
    target: production
    clusters: 1
    values:
      repository: https://github.com/kaizentm/gitops-manifests
      branch: prod
      folder: rancher-hello-world


